workflows:
  ios-app:
    name: FishWise iOS Build
    environment:
      xcode: latest
    scripts:
      - name: Build FishWise App
        script: |
          xcodebuild -project FishWiseApp.xcodeproj -scheme FishWiseApp -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14' build
    artifacts:
      - build/ios/iphonesimulator/*.app